### ISSUE TITLE
mln.mean.sd doesn't work with negative numbers for min.val 

### ISSUE THREAD

**Issue by hsayles** [stmcg/estmeansd#3]
> mln.mean.sd(min.val = -1, med.val = 6, max.val = 11, n = 100)
Error in value[[3L]](cond) : attempt to apply non-function
4: tryCatchOne(expr, names, parentenv, handlers[[1L]])
3: tryCatchList(expr, classes, parentenv, handlers)
2: tryCatch({
       suppressWarnings(stats::optim(par = c(mean.LW, sd.LW), fn = logL))
   }, error = NULL)
1: mln.mean.sd(min.val = -1, med.val = 5, max.val = 10, n = 100)

**Comment by stmcg** [comment]
Hi, 

Thanks for posting. The MLN method is based on a distributional assumption which assumes that the data are positive, and so the `mln.mean.sd` function does not work with negative data. Apologies for the confusing error message.

Feel free to reach out to me at sean_mcgrath@g.harvard.edu if you want to discuss some practical strategies with handling negative data for this type of analysis. 

Best,
Sean
